# Generated by Django 5.2.13 on 2026-04-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_issueditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueditem',
            name='status',
            field=models.CharField(default='accepted', max_length=20),
        ),
    ]
