# Generated by Django 5.2.13 on 2026-04-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_issueditem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueditem',
            name='length',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='issueditem',
            name='size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
