# Generated by Django 5.2.13 on 2026-04-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_issueditem_length_issueditem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueditem',
            name='length',
        ),
        migrations.RemoveField(
            model_name='issueditem',
            name='size',
        ),
    ]
