# Generated by Django 5.2.13 on 2026-04-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_issueditem_length_remove_issueditem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueditem',
            name='length',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issueditem',
            name='size',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
