# Generated by Django 5.2.4 on 2026-04-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
