# Generated by Django 5.2.4 on 2026-04-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventoryitem_department_inventoryitem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='image',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
